spring:
  datasource:
    url: jdbc:postgresql://${DB_PRESS_HOST:localhost}:${DB_PRESS_PORT:5432}/${DB_PRESS_NAME:videos}
    username: ${DB_PRESS_USERNAME:aliya}
    password: ${DB_PRESS_PASSWORD:1901}
    hikari:
      idle-timeout: 300000
      connection-test-query: SELECT 1
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
